name: QuBox Deployment to GitHub Pages
env:
  PUBLISH_DIR: QuboxBlazor/bin/Release/net6.0/publish/wwwroot
on: 
  push:
    branches: [main]
jobs:
  deploy-static-page:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      # uses GitHub's checkout action to checkout code form the master branch
      - uses: actions/checkout@v2
      
      # set up .NET Core SDK
      - uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
      - run: dotnet workload install wasm-tools-net6
      
      # Publish the project in Release mode
      - name: Publish .NET Core Project
        run: dotnet publish QuboxBlazor/QuboxBlazor.csproj -c Release
      
      # copy index.html to 404.html to serve the same file when a file is not found
      - name: copy index.html to 404.html
        run: cp ${{ env.PUBLISH_DIR }}/index.html ${{ env.PUBLISH_DIR }}/404.html
      
      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch ${{ env.PUBLISH_DIR }}/.nojekyll
      
      # Fix the base href issue
      - name: Rewrite base href
        uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
        with:
          html_path: ${{ env.PUBLISH_DIR }}/index.html
          base_href: /Qubox-Sim/
      
      # Commit static resources to GH Pages
      - name: GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.5.1
        with:
          target_branch: gh-pages
          build_dir: ${{ env.PUBLISH_DIR }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
