name: QuBox Deployment to GitHub Pageson 
on: 
  push:
    branches: [main]
jobs:
  deploy-static-page:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      # uses GitHub's checkout action to checkout code form the master branch
      - uses: actions/checkout@v2
      
      # set up .NET Core SDK
      - uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
      
      # publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish QuboxBlazor/QuboxBlazor.csproj -c Release -o release --nologo
      
      # Deploy static page
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: release/wwwroot
